# Generated by Django 5.2.14 on 2026-05-31 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo1_concluido', models.BooleanField(default=False)),
                ('modulo2_concluido', models.BooleanField(default=False)),
                ('modulo2_score', models.IntegerField(default=0)),
                ('modulo2_total', models.IntegerField(default=15)),
                ('modulo3_concluido', models.BooleanField(default=False)),
                ('modulo3_risco', models.CharField(blank=True, max_length=20, null=True)),
                ('modulo3_pontos_risco', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
